name: CI
on:
  push:
    tags-ignore:
      - '*a'
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set TAG
        run: |
          echo 'TAG<<EOF' >> $GITHUB_ENV
          git describe --long >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Set VERSION
        run: echo VERSION=${TAG%%a*} >> $GITHUB_ENV
      - name: Set RELEASE
        run: echo RELEASE=${TAG#*-} >> $GITHUB_ENV
      - name: Set RELEASE2
        run: echo RELEASE=${RELEASE%%-*} >> $GITHUB_ENV
      - name: Build
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
        run: |
          docker build -t chipin/hmr-rpm .
          mkdir -p /tmp/RPMS/x86_64
          sudo chown 111:111 -R /tmp/RPMS
          docker run --rm --name hmr-rpm -v /tmp/RPMS:/home/builder/rpmbuild/RPMS -e VERSION=$VERSION -e RELEASE=$RELEASE chipin/hmr-rpm
          (cd /tmp;tar czf - RPMS) > $TRAVIS_BUILD_DIR/hmr-rpm.tar.gz
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: hmr-rpm.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ env.VERSION }}"
          allowUpdates: true
          replacesArtifacts: true
