name: CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set TAG
        run: echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
      - name: Set VERSION
        run: echo VERSION=${TAG%.*} >> $GITHUB_ENV
      - name: Set RELEASE
        run: echo RELEASE=${TAG##*.} >> $GITHUB_ENV
      - name: Build
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
        run: |
          docker build -t chipin/hmr-rpm .
          mkdir -p /tmp/RPMS/x86_64
          sudo chown 111:111 -R /tmp/RPMS
          docker run --rm --name hmr-rpm -v /tmp/RPMS:/home/builder/rpmbuild/RPMS -e VERSION=$VERSION -e RELEASE=$RELEASE chipin/hmr-rpm
          (cd /tmp;tar czf - RPMS) > $TRAVIS_BUILD_DIR/hmr-rpm.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hmr-rpm.tar.gz
